version: '3'
services:
  postgres:
    image: postgres:12
    container_name: hasura-db
    ports:
      - '5432:5432'
    volumes:
      #- ./db/hasura.sql.gz:/docker-entrypoint-initdb.d/db.hasura.sql.gz
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hasura
      POSTGRES_PASSWORD: hasura

  hasura:
    image: superhumane/hasura-dev-box
    container_name: graphql-engine
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src
    working_dir: /usr/src
    depends_on:
      - 'postgres'

    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
